version: '3'

services:
  db:
    image: postgres:15
    volumes:
      - ./joplindb:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - joplin-net
    env_file:
      - .env

  app:
    image: joplin/server:latest
    depends_on:
      - db
    ports:
      - "127.0.0.1:22300:22300"
    restart: unless-stopped
    networks:
      - joplin-net
    env_file:
      - .env

networks:
  joplin-net:
    driver: bridge
